SELECT 'This is SQL Exercise, Practice and Solution';
SELECT 1, 2, 3;
SELECT 10 + 15;
SELECT 10 / 2;
SELECT * FROM Scientists;
SELECT name AS 'Nome do Projeto', hours AS 'Tempo de Trabalho' FROM Scientists.Projects;
SELECT * FROM Scientists ORDER BY name;
SELECT * FROM Scientists.Projects ORDER BY name;
SELECT CONCAT('O projeto', ' ', name, ' ', 'precisou de', ' ', hours, ' ', 'horas para ser concluído.') AS 'Exercício' FROM Scientists.Projects;
SELECT name, hours FROM Scientists.Projects ORDER BY hours DESC LIMIT 3;
SELECT DISTINCT project FROM Scientists.AssignedTo;
SELECT name FROM Scientists.Projects ORDER BY hours DESC LIMIT 1;
SELECT name FROM Scientists.Projects ORDER BY hours DESC LIMIT 1 OFFSET 1;
SELECT name FROM Scientists.Projects ORDER BY hours LIMIT 5;
SELECT CONCAT('Existem', ' ', CAST(COUNT(name) AS CHAR), ' ', 'cientistas na tabela Scientists.') AS 'Exercício' FROM Scientists;